const User = require("../model/dbconnect");
const postdata = async (req, res) => {
  try {
    if (User) {
      console.log(req.body);
      const Ram = await User.create({
        firstName: req.body.firstName,
        lastName: req.body.lastName,
      });
      console.log("Ram autogenerated id", Ram.id);
      res.send("inserted");
    } else {
      res.send("problm with connected");
    }
  } catch (error) {
    console.log("appjs err", error);
  }
};

const getdata = async (req, res) => {
  try {
    const userget = await User.findAll();
    res.send(userget);
  } catch (error) {
    res.send("err");
  }
};

const updatedata = async (req, res) => {
  const firstName = req.body.firstName;
  const lastName = req.body.lastName;
  id = req.params.id;

  try {
    await User.update(
      { lastName: lastName, firstName: firstName },
      {
        where: {
          id: id,
        },
      }
    );
    res.send("data updated");
  } catch (error) {
    res.send("err");
  }
};
const deletedata = async (req, res) => {
  try {
    // Delete everyone named "Jane"
    const id = req.params.id;
    await User.destroy({
      where: {
        id: id,
      },
    });
    res.send("data deleted");
  } catch (error) {
    console.log("err");
  }
};

module.exports = {
  postdata,
  getdata,
  updatedata,
  deletedata,
};
